import fs from "fs/promises";
import { TemplatePath } from "../typing/autoGenerated";
import path from "path";
import { templatesRoot } from "../consts";

export const loadRawTemplate = async (template: TemplatePath): Promise<string> => {
  return fs.readFile(path.join(templatesRoot, `${template}.template`), { encoding: "utf-8" });
};
